# 넘파이

In [1]:
import numpy as np

array1 = np.array([1,2,3])
print('array1 type:',type(array1))
print('array1 array 형태:',array1.shape)

array2 = np.array([[1,2,3],
                  [2,3,4]])
print('array2 type:',type(array2))
print('array2 array 형태:',array2.shape)

array3 = np.array([[1,2,3]])
print('array3 type:',type(array3))
print('array3 array 형태:',array3.shape)

array1 type: <class 'numpy.ndarray'>
array1 array 형태: (3,)
array2 type: <class 'numpy.ndarray'>
array2 array 형태: (2, 3)
array3 type: <class 'numpy.ndarray'>
array3 array 형태: (1, 3)


[1,2,3]는 (3,)형태로 1차원이고  //  [[1,2,3],[2,3,4]]는 (2,3)형태로 2차원이고  //  [[1,2,3]]는 (1,3) 형태로 2차원이다

대괄호의 갯수에 유의하면 어떤 형태인지 금방 파악할 수 있다

In [2]:
array_int = np.array([1, 2, 3])
array_float = array_int.astype('float64')
print(array_float, array_float.dtype)

array_int1= array_float.astype('int32')
print(array_int1, array_int1.dtype)

array_float1 = np.array([1.1, 2.1, 3.1])
array_int2= array_float1.astype('int32')
print(array_int2, array_int2.dtype)

[1. 2. 3.] float64
[1 2 3] int32
[1 2 3] int32


int형 문자 1, 2, 3을 float형으로 바꾸었더니 1. ,  2. , 3. 이 되었다

반대로 float형 1.1, 2.1, 3.1 을 int형으로 바꾸었더니 1, 2, 3 이 되었다

In [4]:
# 넘파이 배열 쉽게 생성하기
sequence_array = np.arange(10)
print(sequence_array)
print(sequence_array.dtype, sequence_array.shape)
zero_array = np.zeros((3,2),dtype='int32')
print(zero_array)
print(zero_array.dtype, zero_array.shape)
one_array = np.ones((3,2))
print(one_array)
print(one_array.dtype, one_array.shape)

[0 1 2 3 4 5 6 7 8 9]
int32 (10,)
[[0 0]
 [0 0]
 [0 0]]
int32 (3, 2)
[[1. 1.]
 [1. 1.]
 [1. 1.]]
float64 (3, 2)


np.arange() , np.zeros() , np.ones() 를 이용해 배열을 간단하게 만들 수 있다

In [5]:
# 넘파이 배열의 형태 변경하기
array1 = np.arange(10)
print('array1:\n', array1)

array2 = array1.reshape(2,5)
print('array2:\n',array2)

array3 = array1.reshape(5,2)
print('array3:\n',array3)

array1:
 [0 1 2 3 4 5 6 7 8 9]
array2:
 [[0 1 2 3 4]
 [5 6 7 8 9]]
array3:
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


np.reshape을 이용해 넘파이 배열의 형태를 변경할 수 있다 이때 변경할 수 있는 형태는 행렬로 나타낼 수 있어야한다.

In [9]:
# 넘파이 단일 데이터 추출
array1 = np.arange(start=1, stop=10)
print('array1:',array1)
print('맨 뒤의 값:',array1[-1], ', 맨 뒤에서 두번째 값:',array1[-2])

array1d = np.arange(start=1, stop=10)
array2d = array1d.reshape(3,3)
print(array2d)

print('(row=0,col=0) index 가리키는 값:', array2d[0,0] )

array1: [1 2 3 4 5 6 7 8 9]
맨 뒤의 값: 9 , 맨 뒤에서 두번째 값: 8
[[1 2 3]
 [4 5 6]
 [7 8 9]]
(row=0,col=0) index 가리키는 값: 1


배열명[index] 형태로 배열의 특정 데이터값을 추출할 수 있다 ([-1]은 맨 마지막 값)

In [11]:
# 넘파이 슬라이싱
array1 = np.arange(start=1, stop=10)
array3 = array1[0:3]
print(array3)

array1d = np.arange(start=1, stop=10)
array2d = array1d.reshape(3,3)
print('array2d:\n',array2d)
print('array2d[0:2, 0:2] \n', array2d[0:2, 0:2])

[1 2 3]
array2d:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[0:2, 0:2] 
 [[1 2]
 [4 5]]


배열명[idx1:idx2] 형태로 범위 데이터를 추출할 수 있다 고차원의 경우 행렬 범위를 설정해주면 된다

이때 axis=0 이면 '행'  axis=1 이면 '열' 이고 , [:idx]의 형태는 처음부터 idx까지의 범위이다

In [12]:
# 넘파이 조건 추출
array1d = np.arange(start=1, stop=10)
# [ ] 안에 array1d > 5 Boolean indexing을 적용 
array3 = array1d[array1d > 5]
print('array1d > 5 불린 인덱싱 결과 값 :', array3)

array1d > 5 불린 인덱싱 결과 값 : [6 7 8 9]


배열명[조건] 형태로 조건에 맞는 데이터를 추출할 수 있다.

In [14]:
# 행렬의 정렬
org_array = np.array([ 3, 1, 9, 5]) 
print('원본 행렬:', org_array)
# np.sort( )로 정렬 
sort_array1 = np.sort(org_array)         
print ('np.sort( ) 호출 후 반환된 정렬 행렬:', sort_array1) 

sort_array1_desc = np.sort(org_array)[::-1]
print ('내림차순으로 정렬:', sort_array1_desc) 

원본 행렬: [3 1 9 5]
np.sort( ) 호출 후 반환된 정렬 행렬: [1 3 5 9]
내림차순으로 정렬: [9 5 3 1]


np.sort() 로 오름차순 정렬을 할 수 있고 뒤에 [::-1] 을 붙이게 되면 내림차순 정렬을 할 수 있다

In [15]:
# 행렬 연산
A = np.array([[1, 2, 3],
              [4, 5, 6]])
B = np.array([[7, 8],
              [9, 10],
              [11, 12]])

dot_product = np.dot(A, B)
print('행렬 내적 결과:\n', dot_product)

A = np.array([[1, 2],
              [3, 4]])
transpose_mat = np.transpose(A)
print('A의 전치 행렬:\n', transpose_mat)

행렬 내적 결과:
 [[ 58  64]
 [139 154]]
A의 전치 행렬:
 [[1 3]
 [2 4]]


np.dot()로는 행렬의 내적을, np.transpose()로는 전치행렬을 만들 수 있다